<?php

/**
 * @file
 * Contains twitter_pull.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twitter_pull_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the twitter_pull module.
    case 'help.page.twitter_pull':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pulls twitter tweets and display them in a feed') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function twitter_pull_theme($existing, $type, $theme, $path) {
  return array(
    'twitter_pull_tweet_listing' => array(
      'variables' => array(
        'params' => null,
      ),
      'template' => 'twitter_pull_tweet_listing',
    ),
  );
}
